# -*- coding: utf-8 -*-
"""ficha 3 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qPvIA9tFmVXan-wsfnZhJxYmNbGT18Kl
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np

imagem = cv2.imread('Dark_Moon.jpg') #seleciona a imagem desejada
y= int(input('insira o valor inicial da altura '))
x= int(input('insir o valor inicial da largura '))

if y < 0:
  print('O valor que você atribuiu a imagem não pode ser menor que 0')
elif x < 0:
  print('O valor que você atribuiu a imagem não pode ser menor que 0')
else :
  #cv2_imshow(imagem) #mostra a imagem no programa
  heigth = int(input("insira o valor da altura "))
  width = int(input("insir o valor da largura "))
  if heigth < 0:
    print('O valor que você atribuiu a imagem não pode ser menor que 0')
  elif width < 0:
    print('O valor que você atribuiu a imagem não pode ser menor que 0')
  else:
    crop = imagem[y:y+heigth, x:x+width] #nova imagem ja cortada
    cv2_imshow(crop)

