# -*- coding: utf-8 -*-
"""ficha03 - 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhvR3er_U8Rn7Q5A3Bzc12jlAaXyKzW-
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
import imutils

azul = (255, 0, 0)

imagem = cv2.imread("/content/ifhdlfh.jpg")

lower = np.array([0, 0, 0])
upper = np.array([32, 20, 255])
mask = cv2.inRange(imagem, lower, upper)

cnts = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)

for c in cnts:
    aprox = cv2.approxPolyDP(c, 0.01 * cv2.arcLength(c, True), True)
    x, y, w, h = cv2.boundingRect(c)
    aspectRatio = float(w) / h
    if aspectRatio >= 0.95 and aspectRatio <= 1.05:
        cv2.drawContours(imagem, [aprox], -1, azul, 1)
        lower2 = np.array([255, 0, 0])
        upper2 = np.array([255, 0, 0])
        mask2 = cv2.inRange(imagem, lower2, upper2)
        cnts2 = cv2.findContours(mask2.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        cnts2 = imutils.grab_contours(cnts2)
        (x, y), radius = cv2.minEnclosingCircle(aprox)
        center = (int(x), int(y))
        radius = int(radius)
        cv2.circle(imagem, center, radius, (255, 0, 0), 2)
text = "Eu encontrei {} quadrados vermelhos".format(len(cnts2))
cv2.putText(imagem, text, (10,20), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2)

cv2_imshow(imagem)
cv2.waitKey(5000)